config/routes.rb
Stich::Application.routes.draw do
  root 'authentications#new'

  get '/auth/:provider/callback' => 'googleauth#create'

  # New, create, destroy routes for Authentications controller
  get 'authentications/new' => 'authentications#new'
  post 'authentications' => 'authentications#create'
  delete 'authentications' => 'authentications#destroy'

  # New and create routes for Users controller
  get 'authentications/new' => 'users#new'
  post 'users' => 'users#create'
  post 'projects' => 'projects#pull_cards'

  post 'cards/:id/edit' => 'cards#update'
  resources :cards
end

app/models/card.rb
class Card
	include Mongoid::Document
	field :name, type: String
	field :timer, type: String
	
	belongs_to :project

end

app/models/googleauth.rb
class Googleauth < ActiveRecord::Base
  attr_accessible :user_id, :provider, :uid
end

app/models/project.rb
class Project
	include Mongoid::Document
	has_and_belongs_to_many :pusers, class_name: 'User', 
	inverse_of: :uprojects

	field :project_id, type: String

	has_many :cards

	def self.pull_cards(project_id, token)
        search_url = "https://www.pivotaltracker.com/services/v5/projects/#{project_id}/stories?filter=state:delivered,finished,rejected,started,unstarted,unscheduled&limit=20"
        response = HTTParty.get search_url, 
        {:headers => {'X-TrackerToken' => token }}
        if response.to_hash.has_key?("kind") && response["kind"] == "error"
			ids = []
       	else 
		    ids = response.map { |x| x['name'] }
        end
    end
    end	

app/models/user.rb
require 'bcrypt'

class User
	include Mongoid::Document
	has_and_belongs_to_many :uprojects, class_name: 'Project', inverse_of: :pusers 

	attr_accessor :password, :password_confirmation

	field :email, type: String
	field :salt, type: String
	field :hashed_password, type: String
	field :provider, type: String
	field :uid, type: String
	field :token, type: String


before_save :hash_password
validates :email, presence: true
validates :email, uniqueness: {case_sensitive: false}
validates :password, confirmation: true

def self.token
	:token
end

def authenticate (password)
	self.hashed_password ==
	 BCrypt::Engine.hash_secret(password, self.salt)
	end

	private
	def hash_password
		if self.password.present?
			self.salt = BCrypt::Engine.generate_salt
			self.hashed_password = 
			 BCrypt::Engine.hash_secret(password, self.salt)
			password = password_confirmation = nil
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	if session[:user_id]
    	@current_user ||= User.find_by(id: session[:user_id])
  	end
  end

  def authenticate_user
    redirect_to '/authentications/new' unless current_user
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
	before_action :authenticate_user, only: [:destroy]

	def destroy
	    session[:user_id] = nil
	    redirect_to '/authentications/new',
    	notice: "You signed out."
  	end
  	
	def new
		if current_user
			redirect_to cards_url
		else
			@user = User.new
			@newuser = User.new
		end
	end

	def create
    	user = User.find_by(email: params[:user][:email])
	    if user
	        # authenticate user
	        if user.authenticate(params[:user][:password])
	          session[:user_id] = user.id
	          redirect_to cards_url
	        else
	          flash.now.alert = "Unable to sign you in. Please try again."
	          render :new
	        end
	    end
	end

	
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

	def index
		@newcards = Card.new
		@cards = Card.all
		@pivotal_stories = Project.pull_cards(params[:project_id], current_user.token)
	end

	def show
		@card = Card.find(params[:id])
	end

	def new
		@card = Card.new
	end

	def create
		@card = Card.create(params[:card].permit(:name))
		redirect_to edit_cards_url
	end
	def edit
		@card = Card.find(params[:id])
	end

	def update
	  @card = Card.find(params[:id])

	  if @card.update_attributes(params[:card].permit(:name))
	    redirect_to @card
	  else
	  	render 'edit'
	  end
	 end

	def destroy
		@card = Card.find(params[:id]).destroy
		redirect_to cards_url
	end

end

app/controllers/googleauth_controller.rb
class GoogleauthController < ApplicationController
	def index
	  @authentications = current_user.googleauth if current_user
	end

	def create
	  auth = request.env["omniauth.auth"]
	  # user = User.find_or_create_by_provider_and_uid(auth['provider'], auth['uid'])
	  # session[:user_id] = user.id
	  flash[:notice] = "Authentication successful."
	  redirect_to cards_url
	end

	def destroy
	  @authentication = current_user.authentications.find(params[:id])
	  @authentication.destroy
	  flash[:notice] = "Successfully destroyed authentication."
	  redirect_to authentications_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@newuser = User.new
	end

	def create
		@newuser = User.create(params[:user].permit(:email, :password, :password_confirmation, :token))
		redirect_to cards_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentications/destroy.html.erb
Well golly gee

app/views/authentications/index.html.erb
You are on authentications#index

app/views/authentications/new.html.erb
Sign in
<br />
<%= form_for @user, {url:"/authentications", method:"post"} do |u| %>
	<%= u.label :email, "Email" %><%=u.text_field :email %><br />
	
	<%= u.label :password, "Password" %><%=u.text_field :password %><br />
	<%= u.submit "Log In" %>
<% end %>

<%= form_for @newuser do |user| %>
	<p>
		<%= user.label :email, "Email" %>
		<%= user.text_field :email %>
	</p>

	<p>	
		<%= user.label :password, "Password" %>
		<%= user.text_field :password %>
	</p>

	<p>
		<%= user.label :password_confirmation, "Password Confirmation" %>
		<%= user.text_field :password_confirmation %>
	</p>

	<p>
		<%= user.label :token, "API Token" %>
		<%= user.text_field :token %>
	</p>

	<p>	
		<%= user.submit %>
	</p>

	<p>
		<%= link_to "Sign in with Google", '/auth/google_oauth2/' %>
	</p>
	
<% end %>

app/views/cards/edit.html.erb
<%= form_for :card do |card| %>
	<%=card.label :name, "Name" %>
	<%=card.text_field :name %>
	<%=card.submit %>

<% end %>

app/views/cards/index.html.erb
<!-- Form to put in Project ID -->
<%= form_tag cards_path, :method => 'get' do %>
    <%= text_field_tag :project_id, params[:project_id] %>
    <%= submit_tag "Search Project", :name => nil %>
<% end %>
  
<!-- List Stories -->

<% @pivotal_stories.each do |stories| %>
  <p>
    <!-- Code for Timer -->
    <div class="myStopwatch"></div>
    <script type="text/javascript">
      $(function() {
        $('.myStopwatch').stopwatch('theme-1');
      });
    </script>
    <%= form_for @newcards do |u| %>
      <%=u.text_field :name, :value => stories, :readonly => true %><br />
      <script type="text/javascript">
      $('form').on('submit', function(event){
        event.preventDefault();
        $.ajax('/cards', {
          type: 'POST',
          data: $('form').serialize()
        });
      });
      </script>
      <%= u.submit "Submit Time" %>
    <% end %>
  </p>
<% end %>
<%= button_to "Log out", "/authentications/", :method => :delete %>

<% @cards.each do |card| %>

	<%= card.name %>
	<%= button_to "X", {action: "destroy", id: card.id}, {method: :delete, data:{confirm: "Are you sure??"}, :class => "button"} %>
<% end %>

<br>

<!-- JQuery CDN Library for Timer -->
<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

<!-- JQuery for the Timer -->
<script type="text/javascript" src="../assets/jq.stopwatch.min.js"></script>

app/views/cards/new.html.erb
<%= form_for @card do |card| %>
	<%=card.label :name, "Name" %>
	<%=card.text_field :name %>
	<%=card.submit %>

<% end %>

app/views/cards/show.html.erb
<%= @card.name %> 
<%= link_to 'Edit', edit_card_path(@card) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stich</title>
  <% stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <% javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<!-- Load JQuery -->
<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

<!-- Load Timer CSS -->
<link rel="stylesheet" href="/assets/stylesheets/jq.stopwatch.min.css">

<!-- Load Timer JQuery -->
<script type="text/javascript" src="/assets/javascripts/jq.stopwatch.min.js"></script>

<script type="text/javascript" src="/assets/javascripts/test.js"></script>

  <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js' type='text/javascript'>
  </script>
  <link rel="stylesheet" href="../assets/jq.stopwatch.min.css">
</head>
<body>

<%= yield %>

</body>

<!-- Google Auth -->
  <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js' type='text/javascript'>
  </script>



</html>

app/views/timers/index.html.erb
timer#index
<% @timers.each do |timer| %>

	<%= timer.name %>
	<%= button_to "X", {action: "destroy", id: timer.id}, {method: :delete, data:{confirm: "Are you sure??"}, :class => "button"} %>
	
	<%= button_to "Log out", "authentications", method: :delete %>
<form>
      <p>
        <label for='token'>User API Token:</label>
        <input type='text' id='token' />
      </p>
      <p>
	      <label for='project_id'>ID Number of Pivotal Tracker Project:</label>
	      <input type='text' id='project_id' />
      </p>
</form>

<a href='#' id='doit_link'>Fetch Story Names from Project</a>

<div style='margin:40px'>
  <p id='result_title'></p>
  <ul id='result_area'></ul>
</div>

<script type="text/javascript">
  var projectId;

  function executeTrackerApiFetch() {
    // get parameters
    var token = $('#token').val();
    projectId = $('#project_id').val();

    // compose request URL
    var url = 'https://www.pivotaltracker.com/services/v5';
    url += '/projects/' + projectId;
    url += '/stories?filter=state:delivered,finished,rejected,started';
    url += ',unstarted,unscheduled';
    url += '&limit=20';

    // do API request to get story names
    $.ajax({
      url: url,
      beforeSend: function(xhr) {
        xhr.setRequestHeader('X-TrackerToken', token);
      }
    }).done(displayTrackerApiResponse);
  }

  function displayTrackerApiResponse(stories) {
    $('#result_title').html('Unaccepted stories from Project #' + projectId + ' (up to the first 20)');

    var html = '';
    for (var i=0; i < stories.length;i++) {
      html += '<li>' + stories[i].name + '</li>';
    }
    $('#result_area').html(html);
  }

  $(function() {
    $('#doit_link').click(executeTrackerApiFetch);
  });
</script>
<% end %>

<!-- JQuery CDN Library for Timer -->
<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

<!-- JQuery for the Timer -->
<script type="text/javascript" src="../assets/jq.stopwatch.min.js"></script>

<!-- Code for Timer -->
<div id="myStopwatch"></div>
<script type="text/javascript">
  $(function() {
    $('#myStopwatch').stopwatch('theme-1');
  });
</script>

app/views/timers/new.html.erb
<%= form_for @timer do |timer| %>
	<%=timer.label :name, "Name" %>
	<%=timer.text_field :name %>
	<%=timer.submit %>

<% end %>